/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElRow: typeof import('element-plus/es')['ElRow']
    Error: typeof import('./src/components/Result/svg/error.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Info: typeof import('./src/components/Result/svg/info.vue')['default']
    NoFound: typeof import('./src/components/Result/svg/noFound.vue')['default']
    Refresh: typeof import('./src/components/refresh/index.vue')['default']
    Result: typeof import('./src/components/Result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerError: typeof import('./src/components/Result/svg/serverError.vue')['default']
    Success: typeof import('./src/components/Result/svg/success.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Unauthorized: typeof import('./src/components/Result/svg/unauthorized.vue')['default']
    Warning: typeof import('./src/components/Result/svg/warning.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
